/* tslint:disable */
/* eslint-disable */
/**
 * datomic-qbuilder-api
 * TODO...
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  SchemaApiResponse,
} from '../models';
import {
    SchemaApiResponseFromJSON,
    SchemaApiResponseToJSON,
} from '../models';

/**
 * 
 */
export class DatabaseSchemaApi extends runtime.BaseAPI {

    /**
     */
    async apiSchemaGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SchemaApiResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/schema`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SchemaApiResponseFromJSON(jsonValue));
    }

    /**
     */
    async apiSchemaGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SchemaApiResponse> {
        const response = await this.apiSchemaGetRaw(initOverrides);
        return await response.value();
    }

}
