/* tslint:disable */
/* eslint-disable */
/**
 * datomic-qbuilder-api
 * TODO...
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EAVT1 } from './EAVT1';
import {
    EAVT1FromJSON,
    EAVT1FromJSONTyped,
    EAVT1ToJSON,
} from './EAVT1';

/**
 * 
 * @export
 * @interface QueryBuilderModel1
 */
export interface QueryBuilderModel1 {
    /**
     * 
     * @type {Array<object>}
     * @memberof QueryBuilderModel1
     */
    find: Array<object>;
    /**
     * 
     * @type {Array<EAVT1>}
     * @memberof QueryBuilderModel1
     */
    where: Array<EAVT1>;
    /**
     * 
     * @type {Array<object>}
     * @memberof QueryBuilderModel1
     */
    pull: Array<object>;
}

/**
 * Check if a given object implements the QueryBuilderModel1 interface.
 */
export function instanceOfQueryBuilderModel1(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "find" in value;
    isInstance = isInstance && "where" in value;
    isInstance = isInstance && "pull" in value;

    return isInstance;
}

export function QueryBuilderModel1FromJSON(json: any): QueryBuilderModel1 {
    return QueryBuilderModel1FromJSONTyped(json, false);
}

export function QueryBuilderModel1FromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryBuilderModel1 {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'find': json['find'],
        'where': ((json['where'] as Array<any>).map(EAVT1FromJSON)),
        'pull': json['pull'],
    };
}

export function QueryBuilderModel1ToJSON(value?: QueryBuilderModel1 | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'find': value.find,
        'where': ((value.where as Array<any>).map(EAVT1ToJSON)),
        'pull': value.pull,
    };
}

