/* tslint:disable */
/* eslint-disable */
/**
 * datomic-qbuilder-api
 * TODO...
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface QueryBuilderModel
 */
export interface QueryBuilderModel {
    /**
     * 
     * @type {Array<object>}
     * @memberof QueryBuilderModel
     */
    find: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof QueryBuilderModel
     */
    where: Array<object>;
    /**
     * 
     * @type {Array<object>}
     * @memberof QueryBuilderModel
     */
    pull: Array<object>;
}

/**
 * Check if a given object implements the QueryBuilderModel interface.
 */
export function instanceOfQueryBuilderModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "find" in value;
    isInstance = isInstance && "where" in value;
    isInstance = isInstance && "pull" in value;

    return isInstance;
}

export function QueryBuilderModelFromJSON(json: any): QueryBuilderModel {
    return QueryBuilderModelFromJSONTyped(json, false);
}

export function QueryBuilderModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryBuilderModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'find': json['find'],
        'where': json['where'],
        'pull': json['pull'],
    };
}

export function QueryBuilderModelToJSON(value?: QueryBuilderModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'find': value.find,
        'where': value.where,
        'pull': value.pull,
    };
}

