/* tslint:disable */
/* eslint-disable */
/**
 * datomic-qbuilder-api
 * TODO...
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SchemaAttribute } from './SchemaAttribute';
import {
    SchemaAttributeFromJSON,
    SchemaAttributeFromJSONTyped,
    SchemaAttributeToJSON,
} from './SchemaAttribute';

/**
 * 
 * @export
 * @interface SchemaEntity
 */
export interface SchemaEntity {
    /**
     * 
     * @type {string}
     * @memberof SchemaEntity
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SchemaEntity
     */
    _implements?: Array<string>;
    /**
     * 
     * @type {string}
     * @memberof SchemaEntity
     */
    doc?: string;
    /**
     * 
     * @type {Array<SchemaAttribute>}
     * @memberof SchemaEntity
     */
    attributes: Array<SchemaAttribute>;
}

/**
 * Check if a given object implements the SchemaEntity interface.
 */
export function instanceOfSchemaEntity(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "attributes" in value;

    return isInstance;
}

export function SchemaEntityFromJSON(json: any): SchemaEntity {
    return SchemaEntityFromJSONTyped(json, false);
}

export function SchemaEntityFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaEntity {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        '_implements': !exists(json, 'implements') ? undefined : json['implements'],
        'doc': !exists(json, 'doc') ? undefined : json['doc'],
        'attributes': ((json['attributes'] as Array<any>).map(SchemaAttributeFromJSON)),
    };
}

export function SchemaEntityToJSON(value?: SchemaEntity | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'implements': value._implements,
        'doc': value.doc,
        'attributes': ((value.attributes as Array<any>).map(SchemaAttributeToJSON)),
    };
}

