/* tslint:disable */
/* eslint-disable */
/**
 * datomic-qbuilder-api
 * TODO...
 *
 * The version of the OpenAPI document: 0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SchemaEnum
 */
export interface SchemaEnum {
    /**
     * 
     * @type {string}
     * @memberof SchemaEnum
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof SchemaEnum
     */
    doc?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof SchemaEnum
     */
    values: Array<string>;
}

/**
 * Check if a given object implements the SchemaEnum interface.
 */
export function instanceOfSchemaEnum(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "values" in value;

    return isInstance;
}

export function SchemaEnumFromJSON(json: any): SchemaEnum {
    return SchemaEnumFromJSONTyped(json, false);
}

export function SchemaEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): SchemaEnum {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'doc': !exists(json, 'doc') ? undefined : json['doc'],
        'values': json['values'],
    };
}

export function SchemaEnumToJSON(value?: SchemaEnum | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'doc': value.doc,
        'values': value.values,
    };
}

